// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBDAYYLa8yxtiAMmrg4X4K6H4bJ80oKXk',
    appId: '1:988266929167:web:8af957b9dd532922e9977a',
    messagingSenderId: '988266929167',
    projectId: 'campusconnect-c475b',
    authDomain: 'campusconnect-c475b.firebaseapp.com',
    storageBucket: 'campusconnect-c475b.firebasestorage.app',
    measurementId: 'G-X7TYBD8Z6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmTlJF8KCo6uD376dL_tso50lXXm6GDhw',
    appId: '1:988266929167:android:7aa7484f74ef5d13e9977a',
    messagingSenderId: '988266929167',
    projectId: 'campusconnect-c475b',
    storageBucket: 'campusconnect-c475b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmrsZSN0AUwb623ZbiX5J9mGoZ6tmyiX8',
    appId: '1:988266929167:ios:a5d360fd00522cb9e9977a',
    messagingSenderId: '988266929167',
    projectId: 'campusconnect-c475b',
    storageBucket: 'campusconnect-c475b.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmrsZSN0AUwb623ZbiX5J9mGoZ6tmyiX8',
    appId: '1:988266929167:ios:a5d360fd00522cb9e9977a',
    messagingSenderId: '988266929167',
    projectId: 'campusconnect-c475b',
    storageBucket: 'campusconnect-c475b.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBDAYYLa8yxtiAMmrg4X4K6H4bJ80oKXk',
    appId: '1:988266929167:web:57e923a0e6e0f760e9977a',
    messagingSenderId: '988266929167',
    projectId: 'campusconnect-c475b',
    authDomain: 'campusconnect-c475b.firebaseapp.com',
    storageBucket: 'campusconnect-c475b.firebasestorage.app',
    measurementId: 'G-EWLYXM06VX',
  );
}
