// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7oK8LO4i1lJIhXdRKq_IZY7A9l2WCqvI',
    appId: '1:988687394513:web:19afe83d2c73942d9087f0',
    messagingSenderId: '988687394513',
    projectId: 'campusconnect-61042',
    authDomain: 'campusconnect-61042.firebaseapp.com',
    databaseURL: 'https://campusconnect-61042-default-rtdb.firebaseio.com',
    storageBucket: 'campusconnect-61042.firebasestorage.app',
    measurementId: 'G-KY5HT391ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP7cV300yd1govoaKb3OYnVq1RC1sI8eA',
    appId: '1:988687394513:android:64be8c3dc87873b59087f0',
    messagingSenderId: '988687394513',
    projectId: 'campusconnect-61042',
    databaseURL: 'https://campusconnect-61042-default-rtdb.firebaseio.com',
    storageBucket: 'campusconnect-61042.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFxkgDvEcW-9ThOQ_huAslr8jAGl_TZEE',
    appId: '1:988687394513:ios:c34633efc5a3c01e9087f0',
    messagingSenderId: '988687394513',
    projectId: 'campusconnect-61042',
    databaseURL: 'https://campusconnect-61042-default-rtdb.firebaseio.com',
    storageBucket: 'campusconnect-61042.firebasestorage.app',
    iosClientId: '988687394513-kr7cc0cg2g43n8gd90pdb0i0nakaa0vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFxkgDvEcW-9ThOQ_huAslr8jAGl_TZEE',
    appId: '1:988687394513:ios:c34633efc5a3c01e9087f0',
    messagingSenderId: '988687394513',
    projectId: 'campusconnect-61042',
    databaseURL: 'https://campusconnect-61042-default-rtdb.firebaseio.com',
    storageBucket: 'campusconnect-61042.firebasestorage.app',
    iosClientId: '988687394513-kr7cc0cg2g43n8gd90pdb0i0nakaa0vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7oK8LO4i1lJIhXdRKq_IZY7A9l2WCqvI',
    appId: '1:988687394513:web:68aab38d93248eb69087f0',
    messagingSenderId: '988687394513',
    projectId: 'campusconnect-61042',
    authDomain: 'campusconnect-61042.firebaseapp.com',
    databaseURL: 'https://campusconnect-61042-default-rtdb.firebaseio.com',
    storageBucket: 'campusconnect-61042.firebasestorage.app',
    measurementId: 'G-WNHDRE77F3',
  );
}
